[build]
command = "VITE_URL=$URL VITE_DEPLOY_PRIME_URL=$DEPLOY_PRIME_URL VITE_CONTEXT=$CONTEXT pnpm run build"
publish = "dist"

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
