sonar.issue.ignore.multicriteria=sql-string-literals
sonar.issue.ignore.multicriteria.sql-string-literals.ruleKey=plsql:S1192
sonar.issue.ignore.multicriteria.sql-string-literals.resourceKey=supabase/**/*.sql
