-- Migration: recreate public schema from backup analysis
-- Source: db_cluster-06-06-2025_05-21-03.backup---1e514773-25e3-4bb3-ac0c-96207fdeaa6d
-- Project: eucjxbcicejyinubzgwh

-- =====================================================
-- 1. ENUMS
-- =====================================================

CREATE TYPE public.team_type AS ENUM ('player', 'team');

-- =====================================================
-- 2. TABLES
-- =====================================================

-- Table: players
CREATE TABLE public.players (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL
);

COMMENT ON TABLE public.players IS 'Table which holds all players';

-- Table: teams
CREATE TABLE public.teams (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL,
    type public.team_type NOT NULL
);

COMMENT ON COLUMN public.teams.type IS 'Type of the team, single slayer or actual multi member team';

-- Table: team_members
CREATE TABLE public.team_members (
    player_id integer NOT NULL,
    team_id integer NOT NULL
);

-- Table: matches
CREATE TABLE public.matches (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    home_team_id bigint NOT NULL,
    away_team_id bigint NOT NULL,
    in_progress boolean DEFAULT true NOT NULL,
    goals_to_win smallint NOT NULL
);

COMMENT ON COLUMN public.matches.in_progress IS 'Shows if game is still in progress';
COMMENT ON COLUMN public.matches.goals_to_win IS 'How many goals need to be scored for winning the match';

-- Table: goals
CREATE TABLE public.goals (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    goal_time interval NOT NULL,
    player_id bigint,
    team_id bigint NOT NULL,
    match_id bigint NOT NULL
);

COMMENT ON COLUMN public.goals.player_id IS 'Player who scored the goal if known';
COMMENT ON COLUMN public.goals.team_id IS 'Team which scored the goal';
COMMENT ON COLUMN public.goals.match_id IS 'The match in which the goal was scored';

-- Table: profiles
CREATE TABLE public.profiles (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid,
    is_admin boolean DEFAULT false NOT NULL,
    first_name text,
    last_name text,
    email text
);

COMMENT ON TABLE public.profiles IS 'Additional Details for authenticated users';

-- =====================================================
-- 3. PRIMARY KEYS
-- =====================================================

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.team_members
    ADD CONSTRAINT team_members_pkey PRIMARY KEY (player_id, team_id);

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);

-- =====================================================
-- 4. UNIQUE CONSTRAINTS
-- =====================================================

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_email_key UNIQUE (email);

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_user_id_key UNIQUE (user_id);

-- =====================================================
-- 5. FOREIGN KEYS
-- =====================================================

ALTER TABLE ONLY public.team_members
    ADD CONSTRAINT team_members_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id);

ALTER TABLE ONLY public.team_members
    ADD CONSTRAINT team_members_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id);

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_home_team_id_fkey FOREIGN KEY (home_team_id) REFERENCES public.teams(id);

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_away_team_id_fkey FOREIGN KEY (away_team_id) REFERENCES public.teams(id);

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id);

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id);

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id);

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);

-- =====================================================
-- 6. FUNCTIONS
-- =====================================================

CREATE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE user_id = auth.uid() AND is_admin = TRUE
  );
END;
$$;

CREATE FUNCTION public.insert_profile_on_user_creation()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  full_name text;
  first_name text;
  last_name text;
BEGIN
  -- Extract the name from the raw_user_meta_data JSONB column
  full_name := (NEW.raw_user_meta_data->>'name');

  -- Split the full name into first and last names
  IF full_name IS NOT NULL THEN
      first_name := split_part(full_name, ' ', 1);
      last_name := split_part(full_name, ' ', 2);
  ELSE
      first_name := NULL;
      last_name := NULL;
  END IF;

  INSERT INTO public.profiles (user_id, email, first_name, last_name, is_admin)
  VALUES (NEW.id, NEW.email, first_name, last_name, false);

  RETURN NEW;
END;
$$;

-- =====================================================
-- 7. TRIGGERS
-- =====================================================

CREATE TRIGGER after_user_creation
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.insert_profile_on_user_creation();

-- =====================================================
-- 8. ROW LEVEL SECURITY
-- =====================================================

ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- 9. POLICIES
-- =====================================================

-- Players: full access for authenticated users
CREATE POLICY "Enables full access for authenticated Users" ON public.players
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Teams: read access for authenticated users
CREATE POLICY "Enable read access for all users" ON public.teams
    FOR SELECT
    TO authenticated
    USING (true);

-- Team members: full access for authenticated users
CREATE POLICY "Enables full access for authenticated Users" ON public.team_members
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Matches: full access for admin users
CREATE POLICY "Enable full access for Admin users" ON public.matches
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

-- Goals: full access for admin users
CREATE POLICY "Allow Admin Access" ON public.goals
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

-- Profiles: users can insert their own non-admin profile
CREATE POLICY "Users can insert their own profile" ON public.profiles
    FOR INSERT
    TO authenticated
    WITH CHECK ((select auth.uid()) = user_id AND is_admin = false);

-- =====================================================
-- 10. REALTIME PUBLICATION
-- =====================================================

ALTER PUBLICATION supabase_realtime ADD TABLE ONLY public.goals;
ALTER PUBLICATION supabase_realtime ADD TABLE ONLY public.matches;
