-- Migration: event-based scoring data model
-- Introduces match_events as the source of truth for match scoring.
-- Both sensors and web UI submit events; backend derives scores from valid events.
-- See docs/event-based-scoring.md for the full architecture.

-- =====================================================
-- 1. ENUMS
-- =====================================================

CREATE TYPE public.match_event_type AS ENUM (
  'goal_detected',
  'goal_removed',
  'score_reset',
  'manual_correction'
);

CREATE TYPE public.match_event_source AS ENUM (
  'sensor',
  'web',
  'system'
);

CREATE TYPE public.match_event_status AS ENUM (
  'valid',
  'invalid',
  'removed'
);

-- =====================================================
-- 2. TABLE
-- =====================================================

CREATE TABLE public.match_events (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  match_id bigint NOT NULL,
  type public.match_event_type NOT NULL,
  team_id bigint NOT NULL,
  player_id bigint,
  source public.match_event_source NOT NULL,
  source_id text,
  dedupe_key text,
  status public.match_event_status DEFAULT 'valid' NOT NULL,
  goal_time interval,
  metadata jsonb,
  related_event_id bigint
);

COMMENT ON TABLE public.match_events IS 'Append-only event log for match scoring. Sensors and web UI submit events; scores are derived from valid events.';
COMMENT ON COLUMN public.match_events.match_id IS 'The match this event belongs to';
COMMENT ON COLUMN public.match_events.type IS 'Kind of event: goal_detected, goal_removed, score_reset, manual_correction';
COMMENT ON COLUMN public.match_events.team_id IS 'Team the event applies to';
COMMENT ON COLUMN public.match_events.player_id IS 'Player who scored, if known';
COMMENT ON COLUMN public.match_events.source IS 'Origin of the event: sensor, web, or system';
COMMENT ON COLUMN public.match_events.source_id IS 'Identifier of the source (e.g. sensor device ID or user ID)';
COMMENT ON COLUMN public.match_events.dedupe_key IS 'Client-generated key for deduplication (e.g. sensor retry prevention). Unique when provided.';
COMMENT ON COLUMN public.match_events.status IS 'Current status: valid, invalid, or removed';
COMMENT ON COLUMN public.match_events.goal_time IS 'Elapsed match time when the event occurred';
COMMENT ON COLUMN public.match_events.metadata IS 'Extensible JSON payload for additional event data';
COMMENT ON COLUMN public.match_events.related_event_id IS 'References another event this one corrects or supersedes';

-- =====================================================
-- 3. PRIMARY KEY
-- =====================================================

ALTER TABLE ONLY public.match_events
  ADD CONSTRAINT match_events_pkey PRIMARY KEY (id);

-- =====================================================
-- 4. FOREIGN KEYS
-- =====================================================

ALTER TABLE ONLY public.match_events
  ADD CONSTRAINT match_events_match_id_fkey
  FOREIGN KEY (match_id) REFERENCES public.matches(id);

ALTER TABLE ONLY public.match_events
  ADD CONSTRAINT match_events_team_id_fkey
  FOREIGN KEY (team_id) REFERENCES public.teams(id);

ALTER TABLE ONLY public.match_events
  ADD CONSTRAINT match_events_player_id_fkey
  FOREIGN KEY (player_id) REFERENCES public.players(id);

ALTER TABLE ONLY public.match_events
  ADD CONSTRAINT match_events_related_event_id_fkey
  FOREIGN KEY (related_event_id) REFERENCES public.match_events(id);

-- =====================================================
-- 5. INDEXES
-- =====================================================

-- Deduplication: unique only when dedupe_key is provided
CREATE UNIQUE INDEX match_events_dedupe_key_key
  ON public.match_events(dedupe_key)
  WHERE dedupe_key IS NOT NULL;

-- Fast score derivation: all events for a match in chronological order
CREATE INDEX match_events_match_id_created_at_idx
  ON public.match_events(match_id, created_at);

-- =====================================================
-- 6. FUNCTIONS
-- =====================================================

-- Derive the current score for a match from valid goal_detected events.
-- Returns one row per participating team (home and away) with their valid goal count.
-- Teams with zero goals are included via LEFT JOIN against the match row.
CREATE OR REPLACE FUNCTION public.get_match_score(p_match_id bigint)
RETURNS TABLE(team_id bigint, score bigint)
LANGUAGE sql
STABLE
SET search_path TO ''
AS $$
  WITH match_teams AS (
    SELECT m.home_team_id AS tid FROM public.matches m WHERE m.id = p_match_id
    UNION
    SELECT m.away_team_id FROM public.matches m WHERE m.id = p_match_id
  ),
  event_counts AS (
    SELECT
      me.team_id,
      COUNT(*) AS cnt
    FROM public.match_events me
    WHERE me.match_id = p_match_id
      AND me.type = 'goal_detected'
      AND me.status = 'valid'
    GROUP BY me.team_id
  )
  SELECT
    mt.tid AS team_id,
    COALESCE(ec.cnt, 0) AS score
  FROM match_teams mt
  LEFT JOIN event_counts ec ON ec.team_id = mt.tid;
$$;

COMMENT ON FUNCTION public.get_match_score IS 'Returns the current score for a match by counting valid goal_detected events per team.';

-- =====================================================
-- 7. ROW LEVEL SECURITY
-- =====================================================

ALTER TABLE public.match_events ENABLE ROW LEVEL SECURITY;

-- Admin: full access
CREATE POLICY "Enable full access for Admin users" ON public.match_events
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- Authenticated: can view all events
CREATE POLICY "Authenticated users can view match events"
  ON public.match_events
  FOR SELECT
  TO authenticated
  USING (true);

-- Authenticated: can insert events only for active matches
CREATE POLICY "Authenticated users can record events for active matches"
  ON public.match_events
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.matches
      WHERE matches.id = match_events.match_id
        AND matches.in_progress = true
    )
  );

-- Authenticated: can update events (e.g. mark as invalid) only for active matches
CREATE POLICY "Authenticated users can update events for active matches"
  ON public.match_events
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.matches
      WHERE matches.id = match_events.match_id
        AND matches.in_progress = true
    )
  );

-- =====================================================
-- 8. REALTIME PUBLICATION
-- =====================================================

ALTER PUBLICATION supabase_realtime ADD TABLE ONLY public.match_events;
